export const PAGE_SETTING = '/setting'
export const PAGE_CHANGE_PW = '/setting/pw/change'
export const PAGE_CHANGE_NICKNAME = '/setting/nickname/change'
export const PAGE_CHANGE_IMAGE = '/setting/image/change'
export const PAGE_MY_ARTICLE = '/setting/my-article'
export const PAGE_MY_COMMENT = '/setting/my-comment'
