export const ADD_REPLY = 'ADD_REPLY'
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS'
export const ADD_REPLY_ERROR = 'ADD_REPLY_ERROR'

export const GET_REPLY = 'GET_REPLY'
export const GET_REPLY_SUCCESS = 'GET_REPLY_SUCCESS'
export const GET_REPLY_ERROR = 'GET_REPLY_ERROR'

export const UPDATE_REPLY = 'UPDATE_REPLY'
export const UPDATE_REPLY_SUCCESS = 'UPDATE_REPLY_SUCCESS'
export const UPDATE_REPLY_ERROR = 'UPDATE_REPLY_ERROR'

export const DELETE_REPLY = 'DELETE_REPLY'
export const DELETE_REPLY_SUCCESS = 'DELETE_REPLY_SUCCESS'
export const DELETE_REPLY_ERROR = 'DELETE_REPLY_ERROR'
