export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR'

export const GET_COMMENTS_COUNT = 'GET_COMMENTS_COUNT'
export const GET_COMMENTS_COUNT_SUCCESS = 'GET_COMMENTS_COUNT_SUCCESS'
export const GET_COMMENTS_COUNT_ERROR = 'GET_COMMENTS_COUNT_ERROR'
